### ISSUE TITLE
'+ add another' links don't appear on inline forms when using conda environment generated from requirements.txt

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#105]
'+ add another' links don't appear on inline forms when using conda environment generated from requirements.txt
for instance you can't add another featureaction from the sampling feature change form.  
odm2admin/samplingfeatures/1/change/

This doesn't occur on my local development build. I'll see if I can find the package that might be causing this.

**Comment by lsetiawan** [comment]
@miguelcleon I tried replicating this problem, but I don't see any problem.. I am using the environment from requirements.txt

<img width="1393" alt="screenshot 2017-02-03 10 41 34" src="https://cloud.githubusercontent.com/assets/17802172/22603718/55e63280-e9fd-11e6-9ec2-7981224eaebf.png">

**Comment by miguelcleon** [comment]
@lsetiawan Ok, that's interesting, thanks for the input.

**Comment by miguelcleon** [comment]
Ok, I applied the latest updates to ODM2 Admin from master. But I'm still getting the same thing. I'm not sure what is going on then.

**Comment by miguelcleon** [comment]
Ok, I figured it out. Some CSS files weren't loading because they weren't in the static directory on the server. This is fixed now.
