### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/CZ-Manager#11]
@miguelcleon I am unfamiliar with packages that use Djando so I don't really know where to start. Usually the boilerplate is to create a `setup.py` that installs the module, but I believe there are more pieces here that needs to be taken care of. Is that assessment correct?

xref: https://github.com/ODM2/conda-recipes-ODM2/issues/27

**Comment by miguelcleon** [comment]
Ah, this email went into my junk folder. I'll have to look at this a little later

**Comment by miguelcleon** [comment]
I would think that the setup.py file should be able to handle installation of all of the django packages but yes, a user is also going to have to setup the settings.py file which specifies a postgresql server and some system path information. https://github.com/miguelcleon/odm2djangoadmin/blob/master/templatesAndSettings/settings.py

**Comment by miguelcleon** [comment]
Hi, Filipe, I'm back, how do you want to proceed?

**Comment by ocefpaf** [comment]
@miguelcleon I am out until 22nd, but I will put a PR together and we can discuss it once I get back.

**Comment by emiliom** [comment]
Hi guys. I was dropping by to see how the conda packaging work is going. I see @ocefpaf was out until Sunday. Let me know if I can help (though I doubt it ...). Thanks!

**Comment by ocefpaf** [comment]
@miguelcleon and @emiliom the ball is with me now and I need to get a skeleton PR with the boilerplate  first before you can help. I will address this as soon as I get in the US. (I am in transit now with flaky/unreliable connections internet.)

**Comment by emiliom** [comment]
@ocefpaf, I know you're still traveling until the 15th. (We saw each other in DC a week ago, though we didn't have a chance to talk about ODM2, much less odm2djangoadmin.)

Still, I was wondering if you've had a chance to make some progress on packaging this and preparing the PR ... Thanks!

**Comment by ocefpaf** [comment]
Travelling and working :cold_sweat: 
I will have something later today... Hold on...

**Comment by miguelcleon** [comment]
I was traveling myself this week and last, I'm back and around now, after the 15th will work also.

**Comment by emiliom** [comment]
@ocefpaf, it is Friday! Don't feel obligated to make progress today -- though it sounds like you're already doing that! Anyway, it can wait till early next week. @miguelcleon, thanks for chiming in.

**Comment by emiliom** [comment]
@ocefpaf, any recent progress on the packaging? I've kept track of exchanges in your PR (#12), but haven't seen any recent activity.

Thanks!

**Comment by ocefpaf** [comment]
Sorry. No progress. I will make some changes to this PR today to properly package the "data" folder. After that I will need a call @miguelcleon to ask a few questions. How is you next week @miguelcleon? I cannot Monday, but I am free pretty much the rest of the week.

**Comment by miguelcleon** [comment]
I'll be on vacation next week returning July 12th. I can do something today.

**Comment by ocefpaf** [comment]
That works. Ping me once you are back. (Sorry again for the long delay here.)

**Comment by miguelcleon** [comment]
Hi Felipe, I just setup this project again on a new Ubuntu cloud server so it would be a good time for me to work through this with you since I just did it myself. Let me know if you have sometime today or tomorrow.

**Comment by ocefpaf** [comment]
@miguelcleon I am in Austin for SciPy and I can try either 9:15-12:00 or 14:00-16:30 (Central).

Let me know if that works for you. I will be sprinting on conda-forge here next Saturday and I want to address `odm2djangoadmin`.

**Comment by miguelcleon** [comment]
Ok, either of those times will work just give me a call 2157465974

**Comment by emiliom** [comment]
I'm glad you're connecting, and hope that went well. @ocefpaf, enjoy SciPy!

**Comment by miguelcleon** [comment]
@ocefpaf how did it work out? Sounds like you had some ideas about how to move forward. Enjoy SciPy, that sounds cool.

**Comment by emiliom** [comment]
Two updates:
1. I installed ODM2-Admin on my laptop (Ubuntu 14, Postgresql 9.3, PostGIS 2.1, Python 2.7) today! With handholding from @lsetiawan, using his [crossczo branch](https://github.com/lsetiawan/ODM2-Admin/tree/crossczo). We're [installing all dependencies via conda](https://github.com/lsetiawan/ODM2-Admin/blob/crossczo/odm2adminenv.yml), then running ODM2-Admin directly from a local clone of Don's github branch.
2. @ocefpaf is spending some time this week making progress on the conda packaging. Hopefully he'll have some news for us later in the week.

**Comment by miguelcleon** [comment]
great, thanks for the update.

**Comment by emiliom** [comment]
@ocefpaf, were you able to make progress with conda packaging? Thanks.

**Comment by ocefpaf** [comment]
Sorry but no. My laptop keyboard died :-(

I just got an external keyboard now and I am back on the saddle now.

---

Filipe P. A. Fernandes
Physical Oceanographer

Email: ocefpaf@gmail.com

http://ocefpaf.github.io/

---

**Comment by emiliom** [comment]
I feel your pain. My laptop keyboard was dying a slow death a couple of months ago, until I bought a new one.

**Comment by emiliom** [comment]
@ocefpaf, just wondering if you've been able to make more progress over the last week.

Also, how do you recommend that we track progress on this, besides your individual PR's? Is this old issue a good way to go? Or the even older issue at https://github.com/ODM2/conda-recipes-ODM2/issues/27 ?

FYI, @lsetiawan has some time this week and next to help out with testing or other needs involving the conda packaging work, if it's helpful. Just ping him together with @miguelcleon in your PR's.

**Comment by ocefpaf** [comment]
> @ocefpaf, just wondering if you've been able to make more progress over the last week.

I haven't commit anything yet. Working out some priorities on another front.

> Also, how do you recommend that we track progress on this, besides your individual PR's? Is this old issue a good way to go? Or the even older issue at ODM2/conda-recipes-ODM2#27 ?

I'd rather keep things simple. We can use this one as it is pertinent to packaging `ODM2-Admin` and ODM2/conda-recipes-ODM2#27 with regard to the conda-package once this is former is closed.

@lsetiawan or @miguelcleon do you have a time for a call later this week? I would like to ask a few questions regarding testing? (It is complicate to make changes before we have a continuous integration testing framework in place.)

**Comment by lsetiawan** [comment]
@ocefpaf I am available whenever between 8:00 PT to 4:00 PT. Thanks.

**Comment by ocefpaf** [comment]
> @ocefpaf I am available whenever between 8:00 PT to 4:00 PT. Thanks.

How about tomorrow 10:00 PT (14:00 here)? both gtalk and skype username is `ocefpaf`.

**Comment by lsetiawan** [comment]
> How about tomorrow 10:00 PT (14:00 here)? both gtalk and skype username is ocefpaf.

I can do that time. I think @miguelcleon should be there too since he is the main developer for this, and knows about ODM2Admin inside and out. Plus I am also new to the whole thing about testing frameworks. Thanks.

**Comment by ocefpaf** [comment]
I mostly want to get an instance running on my own laptop. Once I can do that I will try to design a simple test to avoid breakages in my following PRs.

**Comment by miguelcleon** [comment]
That sounds good. @lsetiawan do you just want to have a brief chat today call me at 215-746-5974 in the next hour and we can talk about recent changes I've made.

**Comment by lsetiawan** [comment]
@miguelcleon Sure. I will be having lunch soon. Would 1:00 PT work?

**Comment by miguelcleon** [comment]
@ocefpaf  10 AM PT / 1 PM eastern will work to make sure your laptop is setup. let's use gotomeeting so we can do a screen share and I can take control if need be. 
get Felipe setup 
Wed, Sep 21, 2016 1:00 PM - 2:00 PM Eastern Daylight Time 

Please join my meeting from your computer, tablet or smartphone. 
https://global.gotomeeting.com/join/896177693 

You can also dial in using your phone. 
United States +1 (571) 317-3122 

Access Code: 896-177-693 

First GoToMeeting? Try a test session:   http://help.citrix.com/getready

**Comment by miguelcleon** [comment]
@lsetiawan sure, I'll need to make it brief though, I had an early morning and need to head home aroun 4:30 / 1:30 PT.

**Comment by ocefpaf** [comment]
> @ocefpaf 10 AM PT / 1 PM eastern will work

OK.

> Let's use gotomeeting so we can do a screen share and I can take control if need be.

Thanks! I need to see how you are setting up and running `ODM2-Admin` so we can put a simple `.travis.yml` config that does the same and ensure that won't be broken with further changes.

**Comment by emiliom** [comment]
Thanks, all! And @ocefpaf, this sounds good:

> I'd rather keep things simple. We can use this [issue] as it is pertinent to packaging ODM2-Admin and ODM2/conda-recipes-ODM2#27 with regard to the conda-package once this is former is closed.

**Comment by ocefpaf** [comment]
@miguelcleon and @lsetiawan I am in the https://global.gotomeeting.com/join/896177693

**Comment by emiliom** [comment]
@ocefpaf, any updates on progress towards ODM2-Admin packaging? I know the holidays were not the best time to make steady progress .... I just got back myself, and @miguelcleon was away for a week or so. Only @lsetiawan was plugging away steadily :smile_cat: 

I saw your brief exchanges with @lsetiawan on his [most recent ODM2-Admin commit](https://github.com/lsetiawan/ODM2-Admin/commit/f95623495ac8f6548bd6b80d9493084b03d6839f) on his personal fork. He made a couple of [earlier commits on his fork (`dev` branch)](https://github.com/lsetiawan/ODM2-Admin/commits/dev) that also seem like relevant improvements towards packaging, separating code from "data" (user configurations), etc.

Thanks. Happy New Year, all!

**Comment by miguelcleon** [comment]
Hi All,

One thing I'd like to see with this packaging work and changes to settings is adding some switching for enabling or disabling geodjango. In my own development branch https://github.com/miguelcleon/ODM2-Admin/tree/django1.10  I've been working on setting up batch jobs to email time series data. Ideally this should use celery with redis. Geodjango doesn't seem to work with celery though. I also encountered problems running Jupyter Notebooks with Geodjango, so I'd except to continue running into problems that can only be fixed by not using Geodjango for some tasks.

**Comment by emiliom** [comment]
@ocefpaf and @miguelcleon, I see a ton of progress you (and @lsetiawan) have made in the last couple of weeks towards an ODM2-Admin conda packaging. 

@ocefpaf, are you in a position to estimate when a first test conda package may be created? Say, next week??

**Comment by ocefpaf** [comment]
> @ocefpaf, are you in a position to estimate when a first test conda package may be created? Say, next week??

Probably not. There are some lingering issues to resolve,

  1. The common env to build and test is not OK as reported by @miguelcleon in https://github.com/miguelcleon/ODM2-Admin/pull/96#issuecomment-274674964 (we need an issue to track that properly as that PR is unrelated to the problem.)
  2. I am reading to see if PR #96 is the way to go. As a packager I am not OK dropping the extra data as a module in the `site-packages`.
  3. @lsetiawan worked on a nice configuration script somewhere. I recall an e-mail some time ago but I lost track if that became a PR and/or if that was merged.

I am tackling `2` this week. Hopefully we can come up with a solution that won't require extra actions after installation to access that data.

**Comment by emiliom** [comment]
Thanks for the update.

@lsetiawan, can you comment on @ocefpaf's 3rd point?

**Comment by miguelcleon** [comment]
Ok I created a new issue #97

**Comment by miguelcleon** [comment]
@ocefpaf for your item 2. maybe adding another folder layer would do? we could simply move the folders odm2admin, soilsIngestionExample, templatesAndSettings, and tests into an odm2admin folder.

**Comment by lsetiawan** [comment]
@ocefpaf Not sure which configuration you are talking about.. Do mean this one: https://github.com/lsetiawan/ODM2-Admin/commit/f95623495ac8f6548bd6b80d9493084b03d6839f

**Comment by ocefpaf** [comment]
Yes. I do mean those changes.

PS: I am taking a day off today for personal reasons but I will get back to
this tomorrow.

**********************************************************
Filipe P. A. Fernandes
Physical Oceanographer

Email: ocefpaf@gmail.com

http://ocefpaf.github.io/
**********************************************************

**Comment by lsetiawan** [comment]
@ocefpaf Okay. Cool. I never implemented this on master. I will get working on that. Thanks 😸

**Comment by lsetiawan** [comment]
I think this issue can be closed now. We are going in the direction of using Docker atm to ship ODM2-Admin. @miguelcleon Regarding the CLI https://github.com/miguelcleon/ODM2-Admin/issues/11#issuecomment-275174602. Do you think we should still implement this or not? I've never implement it.

**Comment by miguelcleon** [comment]
yeah I think we can close it.

**Comment by lsetiawan** [comment]
@miguelcleon How about 

>Regarding the CLI #11 (comment). Do you think we should still implement this or not? I've never implement it.

**Comment by miguelcleon** [comment]
yeah it seems like adding some CLI commands for setup / configuration could be useful. Did you have some specific things in mind? Ports and the ideas you had here https://github.com/miguelcleon/ODM2-Admin/issues/132 might be handled this way but maybe they would be a different docker container? I think  the existing docker container that just creates a test / local environment is important.
