### ISSUE TITLE
CZO Sampling Feature in map

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/CZ-Manager#115]
@miguelcleon I've been developing the web map to meet the needs of CZIMEA. I have implemented filter by Sampling Feature Type, but I notice that you have a type that is not in the standard library, but rather from an externalidentifier `CZO`. I've been cleaning up and rearranging the code, but wasn't sure how I can put this in.. What was your thought in adding CZO Sampling feature type?

**Comment by miguelcleon** [comment]
Yeah that is kind of a hack. There is not a big reason to keep it.

**Comment by lsetiawan** [comment]
@miguelcleon OK, Great! Lessen my work. Thanks. :) I'll be doing a PR soon.
