### ISSUE TITLE
Map loading slowly

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#150]
@lsetiawan the map view is now loading much more slowly then before. We should add a loading indicator so the user knows that the map is still loading the sampling features. Can something be done to make it load more quickly again?

**Comment by lsetiawan** [comment]
> We should add a loading indicator so the user knows that the map is still loading the sampling features.

Yea. For sure.

> Can something be done to make it load more quickly again?

Not sure yet. There's just a lot of processing on the backend to prepare the json for the front end to use.

**Comment by miguelcleon** [comment]
We added a loading javascript indicator and implemented redis.
