### ISSUE TITLE
change styling to use Django Jet

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#160]
@lsetiawan I'm thinking about using Django Jet for styles and dashboards. This would involve removing djangocms_admin_style. I started playing around with it and it seems really nice. What do you think? 

https://github.com/geex-arts/django-jet

**Comment by lsetiawan** [comment]
@miguelcleon Pretty. I like it! Is it a lot of overhaul?

**Comment by miguelcleon** [comment]
It doesn't seem to be too bad. I have to rip some stuff out of the templates but there aren't that many and it's fairly straightforward 

![image](https://user-images.githubusercontent.com/5941108/30132740-744ec018-931f-11e7-8d75-aef6842d9531.png)

One thing I'm not sure what to change is the map is appearing on top of the side bar (Image below). But maybe you can look at it once I push to a branch you can look at. 

![image](https://user-images.githubusercontent.com/5941108/30132797-b011b06a-931f-11e7-9080-114a47f2d74e.png)

**Comment by miguelcleon** [comment]
I ran into a bug and ended up on this issue https://github.com/geex-arts/django-jet/issues/161 reading this it doesn't  sound good. Maybe this isn't the best idea after all.
