### ISSUE TITLE
add sphinx documentation?

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#163]
@lsetiawan Maybe we can add the Sphinx documentation to ODM2 Admin?

**Comment by lsetiawan** [comment]
We should pull in @ocefpaf for this one, since the setup I am still unfamiliar with.

**Comment by ocefpaf** [comment]
I'll send a PR soon. Note that for the auto-publish stuff I'll need someone with more rights to the repo to add the SSH key.

**Comment by lsetiawan** [comment]
@miguelcleon how about we migrate this repo to ODM2 before doing all this? or @ocefpaf would it not be a big overhaul later on for the docs stuff once it's set up?

**Comment by ocefpaf** [comment]
> or would it not be a big overhaul later on for the docs stuff once it's set up?

The URLs listed in the docs and the `gh-pages` generate would change with the move, but that is not a big deal and easy to change.

**Comment by miguelcleon** [comment]
@lsetiawan Ok, how do we do that? I'm working on an update right now and I'm hoping to do a PR in the next few hours.

**Comment by lsetiawan** [comment]
I think you simply transfer ownership, which is available in settings.

**Comment by miguelcleon** [comment]
Ok I did that.

**Comment by lsetiawan** [comment]
@ocefpaf Now that ODM2-Admin has been moved how do we fix the travis-ci? thanks.

**Comment by ocefpaf** [comment]
Working on it...
