### ISSUE TITLE
Travis failing due to links

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#174]
@ocefpaf  @lsetiawan @emiliom 

I've been adding sphinx documentation for the meeting next week, Travis is failing though because of links that require you to be logged in to a sandbox copy of ODM2 Admin like this link below 

https://dev-odm2admin.cuahsi.org/Sandbox/odm2admin/results/

Here is a travis job that failed. 

https://travis-ci.org/ODM2/ODM2-Admin/jobs/299922357 

The error:

`HTTPSConnectionPool(host='dev-odm2admin.cuahsi.org', port=443): Max retries exceeded with url: /Sandbox/ (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))`

It actually says the certificate failed to be verified, but in any case I just want to suppress the error for now. Is there a way to suppress it?

**Comment by miguelcleon** [comment]
Here is a new one that failed 
https://github.com/ODM2/ODM2-Admin/pull/175

**Comment by emiliom** [comment]
@ocefpaf please help @miguelcleon with this on Friday. @lsetiawan will be busy with other things. Thanks.

**Comment by ocefpaf** [comment]
We can disable the links checks for now. I like to have that "on" to ensure all the links in the docs are live, but those require authentication and, according to a quick test, are getting redirected.

So, until we figure a way to skip and/or fix them (in case the redirects are the desirable destination), I believe that turning links checks off is the quick way forward.

**Comment by miguelcleon** [comment]
Ok, that worked, thank you.
