### ISSUE TITLE
GeoDjango

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#2]
Consider adding GeoDjango API for PostGIS data.

**Comment by emiliom** [comment]
Just adding that PR #20 from @lsetiawan is making headways on this issue. Pretty cool!

**Comment by miguelcleon** [comment]
Yes, this is great! I changed the map center, in a recent [commit](https://github.com/miguelcleon/ODM2-Admin/commit/9208d00c264a30e8eab81a13df7803a3ed0f7258), I'm excited about the possibilities for this.

**Comment by lsetiawan** [comment]
@miguelcleon I think this issue can be closed now. It seems that we have successfully implemented GeoDjango. Thanks
