### ISSUE TITLE
Misspellings on models.py cause errors

### ISSUE THREAD

**Issue by lsetiawan** [ODM2/CZ-Manager#36]
@miguelcleon I noticed that you have a couple misspellings in models.py which lead to errors when trying to retrieve values from the ODM2 database. There are instances that you have misspelled _identifier_ as _identifer_ I fixed this in my code, but now ODM2Admin is messed up when run with your database in few areas such as citations. Thanks 

cc: @emiliom

**Comment by lsetiawan** [comment]
L359 `citationexternalidentiferuri = models.CharField(max_length=255, blank=True, db_column="citationexternalidentiferuri")`

L2395 `variableexternalidentifer = models.CharField(max_length=255)`

**Comment by miguelcleon** [comment]
Yeah we can fix these, I'm pretty certain they had been misspelled in an older release of ODM2 and it carried through.

**Comment by miguelcleon** [comment]
I think I just need to fix my column names on the SQL table after I install your PR.

**Comment by lsetiawan** [comment]
Sounds good. Yea, I did that to your copy database, and it seems to work now. Thanks.

**Comment by emiliom** [comment]
>  I'm pretty certain they had been misspelled in an older release of ODM2 and it carried through

Yeah, this is pretty likely. Sigh. We really need to do a better job on the ODM2 end (ie, the core ODM2 gang) to define schema versions or releases, to make it easier to align ODM2 software like ODM2-Admin with the schema being used.

**Comment by miguelcleon** [comment]
I did fix my column name after I moved your updates live, I'm not sure if this is fixed in the base ODM2 project though.

**Comment by emiliom** [comment]
I haven't seen any noise about fixes in the base ODM2 schema. For later tracking, I'm pasting below the issues Don submitted on the ODM2 repo:
- https://github.com/ODM2/ODM2/issues/129
- https://github.com/ODM2/ODM2/issues/128 (about a controlled vocabulary, not the schema)

In principle I could fix the first one myself; in practice, I haven't been properly set up with DbWrench for a while, I think. Anyway, I'll try to bring it up, to get these fixed.

**Comment by miguelcleon** [comment]
I think this is probably related to this issue but I was having trouble locating the misspelling at the moment. I was trying to delete an organization and I got an error. Can you create and delete an organization? 
![image](https://cloud.githubusercontent.com/assets/5941108/18290852/117f1064-7453-11e6-9152-4ccf9a760043.png)

**Comment by lsetiawan** [comment]
I just tested deleting organization. It is fine for me. No Errors. Thanks. Not sure why you're getting the error...

**Comment by miguelcleon** [comment]
Ok, I had to do the following. I'll check ODM2 package to see if this is an old problem or still present. 

`ALTER TABLE odm2.variableexternalidentifiers  
  RENAME variableexternalidentifer  TO variableexternalidentifier;
`

Ok I checked that is the same issue, just showing up in another place.

**Comment by lsetiawan** [comment]
Yea, I figured that was the Issue, I have brought it up to the main ODM2 as Emilio has mentioned in the comment above. It seems like no fix has been implemented. Glad it works for you now after altering the table.
