### ISSUE TITLE
Enforce a linter for pep8 rules

### ISSUE THREAD

**Issue by ocefpaf** [ODM2/CZ-Manager#46]
@miguelcleon do you want to enforce a linter for [`pep8`](https://www.python.org/dev/peps/pep-0008/) rules here? I usually do that in my code and I even add it as part of the continous integration tests.

(See https://github.com/ocefpaf/ODM2-Admin/blob/Travis-CI/.travis.yml#L28 for example.)

I already started to re-organizing the code in some places but the amount of work required to bring `ODM2-Admin` to compliance is quite a lot. Before taking this path I want to if there is an interest from the authors to continue.

Pros:
- cleaner code;
- lower the entry barrier for new contributors;
- higher maintainability.

Cons:
- too much work;
- authors are a closed group who do not care about `pep8`.

The commit https://github.com/ocefpaf/ODM2-Admin/commit/4fafdebd5363daf9d85bbec274be919b5cafd858 has ~20% of the job done and it is already unmanageable (hard to review without tests). That is the main reason I am raising this issue.

**Comment by emiliom** [comment]
@ocefpaf, personally I'm starting to care more and more about pep8. I haven't looked at ODM2-Admin code with an eye for pep8, but I'm pretty sure the contributions/commits from @lsetiawan (working with me on ODM2-Admin) are not strictly pep8. I believe there are only two developers for ODM2-Admin at this time, @miguelcleon and @lsetiawan.

So, my 2 cents is that this is too much work and not worth it at this time. BUT I'm very interested in getting your help on improving on our ODM2 code base towards pep8, and being prodded regularly :). I suspect it'll be more effective if we dedicate certain commits to pep8 changes alone, when we can dedicate time to it (I'm speaking generally across ODM2, not just ODM2-Admin).

**Comment by miguelcleon** [comment]
It might be nice If perhaps one of the shorter files could be made pep8 compliant as an example. perhaps [https://github.com/miguelcleon/ODM2-Admin/blob/master/ODM2CZOData/lookups.py ](lookups.py) @ocefpaf  maybe you would be willing to take that one on and so we can learn from a practical example? A good thing about using lookup.py is that both myself and @lsetiawan have contributed to this file.

**Comment by emiliom** [comment]
:+1:

**Comment by ocefpaf** [comment]
> @ocefpaf, personally I'm starting to care more and more about pep8.

It can be a pain when working alone but if done from the start it pays off by keeping the code clean and lowering the entry barrier for contributions later on.

> BUT I'm very interested in getting your help on improving on our ODM2 code base towards pep8, and being prodded regularly :)

Let's take a bit size approach then and maybe all the authors can review the errors on Travis-CI and send small PRs addressing some of the issues.

> It might be nice If perhaps one of the shorter files could be made pep8 compliant as an example

Will do. But the best way to check for compliance is to install a linter and run it like the Travis-CI PR is doing. I recommend `flake8` and you can run it like: `flake8 --max-line-length=100 ODM2CZOData/models.py` for example.
