### ISSUE TITLE
Django ORM Srcipts broken in order to pass pep8 

### ISSUE THREAD

**Issue by miguelcleon** [ODM2/CZ-Manager#65]
These files have been broken in order to pass pep8/travis: 

https://github.com/miguelcleon/ODM2-Admin/blob/master/soilsIngestionExample/ImportMStoneData.py 

https://github.com/miguelcleon/ODM2-Admin/blob/master/ODM2CZOData/NewProcessinglevelForTimeSeries.py

They need this at the start:

```
import os
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "templatesAndSettings.settings") 
```

before other django imports, @ocefpaf if we add #noqa to these lines will that work?

**Comment by ocefpaf** [comment]
> before other django imports, @ocefpaf if we add #noqa to these lines will that work?

Not sure what rule they were breaking. Was it the imports below those lines? If that is the case it is rule `E402` and `noqa` won't work. We need to by-pass that rule in Travis-CI. @lsetiawan if you want to go ahead and fix those files I can fix Travis-CI right after the changes.

**Comment by miguelcleon** [comment]
I can fix the files quick @lsetiawan @ocefpaf it maybe easier for me to double check that they work because they are atypical files.

**Comment by lsetiawan** [comment]
@miguelcleon Thanks Miguel, sounds good to me. I won't have time to work on ODM2-Admin today. I'll start looking at your comments tomorrow morning.

**Comment by miguelcleon** [comment]
This applies to this file also 
https://github.com/miguelcleon/ODM2-Admin/blob/master/ODM2CZOData/modelHelpers.py

**Comment by miguelcleon** [comment]
Ok, I just pushed a commit for these three files. @ocefpaf please take a look when you get a chance.  E402 is the problem, so it sounds like we will need to by-pass that rule at least for these files, maybe it is possible to have some kind of flag?

**Comment by miguelcleon** [comment]
Ok I got it to pass by editing travis.yml and ignoring E402 :)

**Comment by ocefpaf** [comment]
> Ok, I just pushed a commit for these three files.

Oops. Sorry. I guess I missed the PR.

> so it sounds like we will need to by-pass that rule at least for these files, 

Ignore E402 per file is not an easy task since https://github.com/PyCQA/pycodestyle/issues/381 was rejected. But it is safe enough to ignore it globally and keep following the rule whenever it makes sense. See my next PR.

**Comment by ocefpaf** [comment]
> Ok I got it to pass by editing travis.yml and ignoring E402 :)

Ah you were quicker... but again I missed the PR :-(

**Comment by ocefpaf** [comment]
@miguelcleon are you committing direct to `master`?

**Comment by miguelcleon** [comment]
yes, in this case I did and have been most of the time.

**Comment by miguelcleon** [comment]
I could not do that. @ocefpaf

**Comment by ocefpaf** [comment]
> yes, in this case I did and have been most of the time.

OK. That explain why I could not see the changes :smile: 

Either way I am rebasing my PR so we can clean this up a little bit more.

**Comment by ocefpaf** [comment]
> I could not do that. @ocefpaf

It is highly recommend but this is your project so it is your choice.

**Comment by miguelcleon** [comment]
Ok, I can understand why, just worked on it by myself for so long, I got used to it. But I can see why it  would be better fork and stage things, especially to keep the project in a passing state on travis.

**Comment by ocefpaf** [comment]
> Ok, I can understand why, just worked on it by myself for so long,

I am guilt. I do that in all my projects, when I am alone :smile: but good practices, like not commit to `master`, are better for aggregating a community around your project.

**Comment by lsetiawan** [comment]
@miguelcleon I have the new rebased viewonly capability ready to be pushed. Is there a way that you can add like a `development` branch for staging/testing purposes? I think it would be a good idea. Thanks

**Comment by miguelcleon** [comment]
OK I created a testing branch and cleaned up some other branches.
