### ISSUE TITLE
.gitignore changes to better handle jupyter notebooks, etc

### ISSUE THREAD

**Issue by emiliom** [ODM2/CZ-Manager#79]
In my notes from our call last Friday I wrote that I was going to make tweaks to your `.gitignore` file. For now, the simplest way for me to do this (instead of a PR) is to list them here and have you apply them. Sorry ...

**Remove:**
`*.ipynb`

I would remove `.gitignore` from the list, so that changes to it are propagated. But there are probably different schools of thought on that.

**Add:**
`.ipynb_checkpoints`

You might as well also add these two, that are generally good to have:
`*~`
`.DS_Store`

**Comment by miguelcleon** [comment]
Ok, thank you @emiliom I've made the suggested changes.
