### ISSUE TITLE
Rename ODM2CZOData folder to something more generic, eg, odm2admin?

### ISSUE THREAD

**Issue by emiliom** [ODM2/CZ-Manager#82]
@miguelcleon, is having a base folder name `ODM2CZOData` necessary or even helpful at this point? It doesn't seem like it.

As we prepare to make a last push (hopefully) on [conda packaging](#11), plus improvements to the setup/configurations that @lsetiawan has made recently (see [his commits on his branch since 12/20](https://github.com/lsetiawan/ODM2-Admin/commits/dev)), this is a good time to think about this. It seems to me to like `ODM2CZOData` is a holdover that now just adds confusion. Assuming I'm right, I'd suggest renaming to `odm2admin`. 

@ocefpaf, any thoughts on good practices for that "base" code folder?

**Comment by miguelcleon** [comment]
@emiliom we should be able to change the name of the folder. I don't think the current name is particularly good or useful.

**Comment by miguelcleon** [comment]
@emiliom This is addressed in this PR https://github.com/miguelcleon/ODM2-Admin/pull/89/files I've renamed the folder odm2admin. I'll merge this later unless @ocefpaf has anything to add.

**Comment by ocefpaf** [comment]
Right now, no. I am working on how to ship the extra data files. PR later today...

**Comment by miguelcleon** [comment]
Ok great. Merging now.

**Comment by emiliom** [comment]
Thanks!
